inherit_from:
  - rubocop-treatwell-style.yml

AllCops:
  NewCops: enable

# Is not a rails project
Rails:
  Enabled: false

Naming/FileName:
 Exclude:
   - lib/rubocop-treatwell.rb

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/rubocop/treatwell.rb'
